[package]
name = "p2db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.1.0"
subprocess = "0.2.9"
clap = { version = "3.1.18", features = ["derive"] }